version: "3.3"

services:

# REDIS #

  redis:
    container_name: redis
    build: ./services/redis
    ports:
      - "6380:6379"
    networks:
      - transcendence
    restart: on-failure

# DJANGO #

  django:
    container_name: django
    depends_on:
      - postgres
      - redis
    networks: 
      - transcendence
    build:
      context: ./services/django
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - static_files:/transcendence/static
      - media_files:/transcendence/media
    restart: on-failure

# NGINX #

  nginx:
    container_name: nginx
    depends_on:
      - django
    networks:
      - transcendence
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    ports:
      - "8433:8433"
      - "8443:8443"
    volumes:
      - ./services/django/transcendence:/transcendence  # DEV PHASE ONLY, allow direct code modification inside the container
      - static_files:/static
      - media_files:/media
    restart: on-failure

# POSTGRESQL #

  postgres:
    container_name: postgres
    networks:
      - transcendence
    build:
      context: ./services/postgres
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "4321:4321"
    restart: on-failure

###########################################
#################START_ELK#################
###########################################

  # ELASTICSEARCH #

  elasticsearch:
    image: elasticsearch:8.15.5
    container_name: elasticsearch
    networks:
      - transcendence
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"

  # KIBANA #

  kibana:
    image: kibana:8.15.5
    container_name: kibana
    networks:
      - transcendence
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  # LOGSTASH #

  logstash:
    image: logstash:8.15.5
    container_name: logstash
    networks:
      - transcendence
    ports:
      - "5000:5000"
    volumes:
      - ./services/logstash/conf/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch

###########################################
##################END_ELK##################
###########################################

volumes:
  static_files:
    driver: local
  media_files:
    driver: local

networks:
  transcendence:
    driver: bridge
